# Generated by Django 4.0.6 on 2023-01-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_address_profile_education_profile_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
