# Generated by Django 3.2.16 on 2023-01-28 07:24

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_account_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', users.models.CustomAccountManager()),
            ],
        ),
    ]
