# Generated by Django 3.2.16 on 2023-01-14 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constant', '0003_category_direction_status'),
        ('institutions', '0004_alter_job_degree_needed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.department')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constant.direction')),
            ],
            options={
                'verbose_name': 'Лоиҳа',
                'verbose_name_plural': 'Лоиҳаҳо',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constant.category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constant.status')),
            ],
            options={
                'verbose_name': 'Мавзуъ',
                'verbose_name_plural': 'Мавзуъҳо',
            },
        ),
    ]
