# Generated by Django 3.2.16 on 2023-01-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constant', '0003_category_direction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20230115_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('aproved', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Нақшаи инфродӣ',
                'verbose_name_plural': 'Нақшаҳои инфродӣ',
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('excepted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('article_info', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.plan')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constant.status')),
            ],
            options={
                'verbose_name': 'Боб',
                'verbose_name_plural': 'Бобҳо',
                'ordering': ('due_date',),
            },
        ),
    ]
