# Generated by Django 4.0.6 on 2023-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_plan_subtopic_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='print_list',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='print_list',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
