# Generated by Django 3.2.16 on 2023-01-15 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constant', '0003_category_direction_status'),
        ('institutions', '0004_alter_job_degree_needed'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ('due_date',), 'verbose_name': 'Боб', 'verbose_name_plural': 'Бобҳо'},
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constant.status'),
        ),
        migrations.CreateModel(
            name='User_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('disabled', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вазифаи кормонд',
                'verbose_name_plural': 'Вазифаҳои кормандон',
            },
        ),
    ]
