# Generated by Django 3.2.16 on 2023-01-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230115_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_job',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
