# Generated by Django 3.2.16 on 2023-01-15 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constant', '0003_category_direction_status'),
        ('main', '0003_alter_user_job_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_job',
            options={'verbose_name': 'Вазифаи корманд', 'verbose_name_plural': 'Вазифаҳои кормандон'},
        ),
        migrations.AddField(
            model_name='subtopic',
            name='article_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('program_date', models.DateField()),
                ('tv_name', models.CharField(max_length=255)),
                ('tv_program', models.CharField(blank=True, max_length=255, null=True)),
                ('program_link', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constant.category')),
            ],
            options={
                'verbose_name': 'Телевизион',
                'verbose_name_plural': 'Телевизионҳо',
            },
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('program_date', models.DateField()),
                ('radio_name', models.CharField(max_length=255)),
                ('radio_program', models.CharField(blank=True, max_length=255, null=True)),
                ('program_link', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constant.category')),
            ],
            options={
                'verbose_name': 'Радио',
                'verbose_name_plural': 'Радиоҳо',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('conf_date', models.DateField()),
                ('conf_name', models.CharField(max_length=255)),
                ('conf_place', models.CharField(max_length=255)),
                ('conf_link', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constant.category')),
            ],
            options={
                'verbose_name': 'Конфронсу семинар',
                'verbose_name_plural': 'Конфронсу семинарҳо',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('annotation', models.TextField()),
                ('pages', models.PositiveIntegerField(max_length=3)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('pub_place', models.CharField(blank=True, max_length=255, null=True)),
                ('pub_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('edited_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constant.category')),
            ],
            options={
                'verbose_name': 'Китоб',
                'verbose_name_plural': 'Китобҳо',
            },
        ),
        migrations.CreateModel(
            name='Article_pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pages', models.PositiveIntegerField(max_length=3)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('pub_place', models.CharField(blank=True, max_length=255, null=True)),
                ('pub_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('edited_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constant.category')),
            ],
            options={
                'verbose_name': 'Мақолаи оммавӣ',
                'verbose_name_plural': 'Мақолаҳои оммавӣ',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('annotation', models.TextField()),
                ('pages', models.PositiveIntegerField(max_length=3)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('pub_place', models.CharField(blank=True, max_length=255, null=True)),
                ('pub_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('edited_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constant.category')),
            ],
            options={
                'verbose_name': 'Мақола',
                'verbose_name_plural': 'Мақолаҳо',
            },
        ),
    ]
