# Generated by Django 4.0.6 on 2023-01-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230115_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf/scientific', verbose_name='PDF-Файл'),
        ),
        migrations.AddField(
            model_name='article_pub',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf/public', verbose_name='PDF-Файл'),
        ),
    ]
