# Generated by Django 4.0.6 on 2023-01-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_article_pdf_file_article_pub_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_pub',
            name='pages',
            field=models.PositiveIntegerField(),
        ),
    ]
