# Generated by Django 4.0.6 on 2023-01-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf/books', verbose_name='PDF-Файл'),
        ),
    ]
