# Generated by Django 4.0.6 on 2023-01-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_article_pdf_file_alter_article_pub_pdf_file_and_more'),
        ('main', '0011_auto_20230128_1115'),
    ]

    operations = [
    ]
