# Generated by Django 3.2.16 on 2023-01-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constant', '0001_initial'),
        ('institutions', '0003_auto_20230114_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='degree_needed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constant.education'),
        ),
    ]
