# Generated by Django 3.2.16 on 2023-01-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_alter_job_degree_needed'),
        ('constant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Degree',
        ),
    ]
